name: CI/CD

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Install Maven
              run: |
                  sudo apt-get update
                  sudo apt-get install -y maven

            - name: Build the project
              run: |
                  mvn clean install

            - name: Run tests
              run: |
                  mvn test

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: success()
        steps:
            - name: Deploy to production
              run: |
                  # commands to deploy the jar file to production here