name: CI/CD
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Cache JDK
              uses: actions/cache@v2
              with:
                path: /usr/lib/jvm/java-11-openjdk-amd64
                key: java-11-openjdk-amd64-${{ hashFiles('**/java-11-openjdk-amd64/**') }}

            - name: Install Maven
              run: |
                  sudo apt-get update
                  sudo apt-get install -y maven
            - name: Cache Maven
              uses: actions/cache@v2
              with:
                path: /usr/share/maven
                key: maven-${{ hashFiles('**/usr/share/maven/**') }}

            - name: Build the project
              run: |
                  mvn clean compile
            - name: Install Node.js
              run: sudo apt-get install -y nodejs
            - name: Cache Node.js
              uses: actions/cache@v2
              with:
                path: /usr/local/bin/node
                key: node-${{ hashFiles('**/usr/local/bin/node/**') }}

            - name: Install json-server
              run: npm install -g json-server
            - name: Cache json-server
              uses: actions/cache@v2
              with:
                path: /usr/local/lib/node_modules/json-server
                key: json-server-${{ hashFiles('**/usr/local/lib/node_modules/json-server/**') }}

            - name: Run json-server
              run: json-server db.json --port=8080 &
            - name: Run tests
              run: |
                  mvn test

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: success()
        steps:
            - name: Deploy to production
              run: |
                  # commands to deploy the jar file to production here